#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

mkdir -p tmp
git show HEAD:releases.json > tmp/base-releases.json
script/goreleases check-conflicts tmp/base-releases.json releases.json
