name: update
on:
  workflow_dispatch: { }
  schedule:
    - cron: '35 * * * *'
jobs:
  update-releases:
    name: update releases.json
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: script/update-releases
      - name: script/validate-releases
        id: validate
        run: |
          if ./script/validate-releases; then
            echo "::set-output name=validated::true"
          else
            echo "::set-output name=validated::false"
          fi
      - name: update branch
        if: ${{ steps.validate.outputs.validated == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: Workflow <noreply@github.com>
          commit_message: update releases.json
      - name: Create Pull Request
        if: ${{ steps.validate.outputs.validated == 'false' }}
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update releases.json
          title: releases.json updates
          branch: updates
          committer: Workflow <noreply@github.com>
          author: Workflow <noreply@github.com>
          delete-branch: true
