name: update
on:
  workflow_dispatch: { }
  schedule:
    - cron: '35 * * * *'
jobs:
  update-releases:
    name: update releases.json
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: script/update-releases
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update releases.json
          title: releases.json updates
          branch: updates
          committer: Workflow <noreply@github.com>
          author: Workflow <noreply@github.com>
          delete-branch: false
      - name: set latest
        run: |
          created_pr='${{ steps.create-pull-request.outputs.pull-request-number }}'
          git switch latest 2>/dev/null || git switch -c latest
          git fetch origin
          git reset --hard origin/main
          if [ -n "$created_pr" ]; then
            git reset --hard origin/updates
          fi
          git push -f -u origin latest
